name: Setup KiCad
description: Install and setup KiCad.

inputs:
  version:
    description: the X.Y KiCad version to install
    required: false
    default: '9.0'

runs:
  using: composite
  steps:
    - name: add KiCad PPA
      shell: bash
      run: |
        sudo apt-add-repository --yes ppa:kicad/kicad-${{ inputs.version}}-releases
        sudo apt-get update

    - name: install KiCad
      shell: bash
      run: sudo apt-get install --yes kicad

    - name: use default KiCad library tables
      shell: bash
      run: |
        mkdir -p ~/.config/kicad/$(kicad-cli -v | cut -d . -f 1,2)
        cp /usr/share/kicad/template/*-lib-table ~/.config/kicad/$(kicad-cli -v | cut -d . -f 1,2)

    - name: print KiCad version
      shell: bash
      run: |
        kicad-cli version
        kicad-cli version --format=commit
        kicad-cli version --format=about
