on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    name: Demonstration Board
    steps:
      - uses: actions/checkout@v4
      - uses: ./setup

      - id: preview-pcb
        uses: ./preview-pcb
      - id: schematic
        uses: ./schematic
      - id: erc
        uses: ./erc
      - id: drc
        uses: ./drc

      - uses: actions/upload-artifact@v4
        with:
          name: generated
          path: |
            ${{ steps.preview-pcb.inputs.output-top }}
            ${{ steps.preview-pcb.inputs.output-bottom }}
            ${{ steps.schematic.inputs.output }}
            ${{ steps.erc.inputs.output }}
            ${{ steps.drc.inputs.output }}
